[package]
name = "website-api-data"
version = "0.1.0"
edition = "2024"

[lib]
name = "website_api_data"
path = "lib.rs"

[dependencies]
axum = { workspace = true }
chrono = { workspace = true }
directories = { workspace = true }
serde = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
